[package]
name = "benchmark_db"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
pcap = "2.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

packet_parser = { path = "../" }

chrono = "0.4.42"